#!/bin/env bash
#
# This script stands in for a bi-directional serial link connecting a
# device called LHS (left hand side) to a device called RHS (right
# hand side). The LHS is this script and the RHS is you (on the
# terminal).
#
# Data generated by the LHS is written to stdout. Responses from the
# RHS are read from stdin.
#
# For logging, LHS output is written to stderr as "LHS: Sending
# <whatever>", and LHS input is written to stderr as "LHS: Received
# <whatever>".
#
# The LHS starts by sending "HELLO", waits for a response from RHS,
# then sends "HELLO" again, until the response is 'quit".
#
set -e

while true; do
    echo "HELLO"
    echo "LHS: Sending \"HELLO\"" 1>&2

    read inputline
    echo "LHS: Received \"$inputline\"" 1>&2
    if [[ $inputline == quit ]]
    then
        echo "LHS: bye" 1>&2
        exit 1
    fi
done
